Adding ability for temp controller to be disconnected.
lsst-ts/ts_TunableLaser pull request #38
Opened 2024-02-22 18:55 UTC by JosephParsons

2024-03-25 14:36 UTC, JosephParsons commented
Parker has confirmed it works in the lab.

2024-03-25 19:55 UTC, couger01 requested changes
Had a few suggestions.

2024-03-25 19:55 UTC, couger01 commented on python/lsst/ts/tunablelaser/component.py
> +        # if host is not valid IP address assume its unconnected
Do we want to restrict to only IP addresses and not have hostname/DNS support?

2024-03-25 19:55 UTC, couger01 commented on python/lsst/ts/tunablelaser/component.py
> +            self.host = "unconnected"
I think self.host should be None.

2024-03-25 19:55 UTC, couger01 commented on python/lsst/ts/tunablelaser/interfaces.py
> +        if self.host != "unconnected":
This should be `self.host is not None`

2024-03-25 19:55 UTC, couger01 commented on tests/data/config/disconnected_temp_ctrl.yaml
Add a newline.

2024-04-12 18:35 UTC, parfa30 commented
Is this ready to go?

2024-04-16 18:37 UTC, couger01 commented on python/lsst/ts/tunablelaser/interfaces.py
> +        # TODO remove if jenkins pass
Remove this todo or add a ticket to it.

2024-04-16 18:38 UTC, couger01 commented on python/lsst/ts/tunablelaser/mock_server.py
> +                port=50,
Don't default to 50 as that is a privileged port and can cause issues with the CI.

2024-04-18 17:30 UTC, couger01 approved these changes
LGTM.

2024-04-18 18:39 UTC, merged