Tickets/DM-40029
lsst-ts/ts_TunableLaser pull request #42
Opened 2024-03-25 16:25 UTC by kfanning

* Added call to `maxi_opg.set_configuration` in `MainLaser.configure` to set optical alignment of the laser when connecting to hardware. This fixes the bug reported in DM-40029 and adds the expected behavior that alignment will match what is in the configuration.
 * Started writing to evt_opticalConfiguration to reflect the state of the optical alignment.

* Features to change opticalConfiguration on the fly will come in DM-41426

2024-03-25 20:09 UTC, couger01 requested changes
Can you run `towncrier create DM-40029.bugfix.rst` and write a note about your fix?

2024-03-25 22:11 UTC, kfanning commented
> Can you run `towncrier create DM-40029.bugfix.rst` and write a note about your fix?

Can do. Is towncrier included in the docker image for lsst-ts?

Also expect further changes. Trying to get DM-41426 wrapped up made me realize this likely won't work on hardware. I am calling it to change configuration before the CSC is connected to the hardware. Jenkins had a warning that I should have paid more attention to:
`MaxiOPG.set_configuration' was never awaited`
When it is awaited it times out since it is not connected.

2024-03-26 14:51 UTC, couger01 commented
Town crier should be included I think.

2024-04-11 15:16 UTC, couger01 commented
Should this PR be closed since #45 covers this one?

2024-04-11 15:23 UTC, closed without merging